import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LaunchesList from '../components/LaunchesList';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Top Launches</h1>
        <LaunchesList />
      </main>

      <footer className={styles.footer}>Made by Matt Greenfield</footer>
    </div>
  );
}
